name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto_assign_job:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign to Author
      - uses: betty.dev/auto-assign-action@v1
      with:
        addReviewers: true
        addAssignees: author
        reviewers:
          - betty-godier
        numberOfReviewers: 1
        runOnDraft: true
