name: Auto Assign to Pull Requests

on: 
  pull_request:
    types: [opened]

jobs:
  auto_assign_job:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign to a specific assignee
        uses: actions/github-script@v6
        with:
          script: |
            // Add assignee
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            assignees: ['betty-godier']
            })
